# File: configs/config.yaml
schedule: "@every 30m"

smtp:
  host: "${SMTP_HOST}"
  port: ${SMTP_PORT}
  username: "${SMTP_USER}"
  password: "${SMTP_PASS}"
  from: "${SMTP_FROM}"
  to:
    - "${SMTP_TO1}"
    - "${SMTP_TO2}"

modules:
  - ip
  - os
  - cpu
  - mem
  - users

http:
  addr: ":8080"
