# File: .github/workflows/ci.yml
name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19, 1.20, 1.21]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with: go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...
      - name: Build binary
        run: GOOS=linux GOARCH=amd64 go build -o server-gen ./cmd/server-gen
      - name: Lint
        run: go vet ./...
